CREATE DATABASE IF NOT EXISTS expense_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE expense_db;

CREATE TABLE IF NOT EXISTS chitieu (
  MACT INT(11) NOT NULL AUTO_INCREMENT,
  MUCDICHCHITIEU VARCHAR(100) NOT NULL,
  IDNHANVIEN INT(11) DEFAULT NULL,
  SOTIEN DECIMAL(15,0) NOT NULL,
  NGAYCHITIEU DATETIME DEFAULT CURRENT_TIMESTAMP,
  GHICHU TEXT DEFAULT NULL,
  TRANGTHAI TINYINT(1) DEFAULT NULL,
  LOAI VARCHAR(30) NOT NULL DEFAULT 'other',
  DANHMUC VARCHAR(50) NOT NULL DEFAULT 'other',
  REF_CODE VARCHAR(120) DEFAULT NULL,
  IS_DELETED TINYINT(1) NOT NULL DEFAULT 0,
  DELETED_AT DATETIME DEFAULT NULL,
  PRIMARY KEY (MACT),
  KEY idx_chitieu_nhanvien (IDNHANVIEN),
  KEY idx_chitieu_ngay (NGAYCHITIEU),
  KEY idx_chitieu_loai (LOAI),
  KEY idx_chitieu_danhmuc (DANHMUC),
  KEY idx_chitieu_deleted (IS_DELETED),
  UNIQUE KEY uq_chitieu_ref_code (REF_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO chitieu (MACT, MUCDICHCHITIEU, IDNHANVIEN, SOTIEN, NGAYCHITIEU, GHICHU, TRANGTHAI, LOAI, DANHMUC, REF_CODE, IS_DELETED, DELETED_AT) VALUES
(10001, 'Thanh Toan Luong', 10003, -600000, '2026-01-03 12:15:33', 'Du lieu cu tu user_db', 1, 'salary', 'salary', 'LEGACY-SALARY-10001', 0, NULL),
(10002, 'Tra dien', 10003, 200000, '2026-01-03 16:45:44', 'Du lieu cu tu user_db', 1, 'other', 'electric', 'LEGACY-OTHER-10002', 0, NULL),
(10003, 'Tien nuoc', 10003, 20000, '2026-01-03 19:58:35', '', NULL, 'other', 'water', 'LEGACY-OTHER-10003', 0, NULL);

ALTER TABLE chitieu
  MODIFY MACT int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10004;
